---
- name: Install programms
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ repo_list }}"

- name: Add tmux.conf on server
  become: yes
  copy:
    src: "{{ files/ | default() }}.tmux.conf"
    dest: "/root/tmux.conf"
