---
- name: Check OS and install
  become: yes
   setup:
    filter:
      - os_family
  
- name: Set default value if an item is not present in the list
  set_fact:
    repo_file: "{{ ansible_facts['os_family'] | lower }}"

- name: Include tasks for the proper OS
  include_tasks: "{{ repo_file }}"
