---
- name: Install programms
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ program_list }}"

- name: Add tmux.conf on server
  become: yes
  copy:
    src: "{{ files | default() }}.tmux.conf"
    dest: "/root/.tmux.conf"
